language: java
jdk:
  - openjdk8

branches:
  only:
    - master

script: "./Single-development_Websites/FirstSpringProject/gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ccc96360@naver.com

